name: Threadfin Beta Build
on:
  push:
    branches:
      - beta
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: beta

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Build Linux
        run: |
          mkdir -p dist
          echo "Building Linux"
          env GOOS=linux GOARCH=amd64 go build -mod=mod -o dist/Threadfin_linux_amd64
